import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import Hero from "@/components/Hero";
import ScrollDown from "@/components/ScrollDown";

import Career from "@/components/Career/Career";
import About from "@/components/About";
import { useState } from "react";
import { Router, useRouter } from "next/router";

const inter = Inter({ subsets: ["latin"] });
export default function Home() {
  return (
    <>
      <Head>
        <title>elbjek | 2023</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <ScrollDown />
        <Hero />
        <About />
        <Career />
      </main>
    </>
  );
}
